schema = 3

[mod]
  [mod."github.com/machinebox/graphql"]
    version = "v0.2.2"
    hash = "sha256-aFl2nxbzJd7il8roqVoVvfUvHZTd5/A9D1V4r3TEykg="
  [mod."github.com/matryer/is"]
    version = "v1.4.1"
    hash = "sha256-OYbpUlsAJfkMfuizteYBtRXqjfJWSnSJKioFKySCjxM="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."golang.org/x/time"]
    version = "v0.5.0"
    hash = "sha256-W6RgwgdYTO3byIPOFxrP2IpAZdgaGowAaVfYby7AULU="
